
time.o:	/usr/include/ansi.h
time.o:	/usr/include/limits.h
time.o:	/usr/include/machine/interrupt.h
time.o:	/usr/include/minix/com.h
time.o:	/usr/include/minix/config.h
time.o:	/usr/include/minix/dir.h
time.o:	/usr/include/minix/endpoint.h
time.o:	/usr/include/minix/limits.h
time.o:	/usr/include/minix/minlib.h
time.o:	/usr/include/minix/sys_config.h
time.o:	/usr/include/minix/sysinfo.h
time.o:	/usr/include/minix/type.h
time.o:	/usr/include/minix/types.h
time.o:	/usr/include/signal.h
time.o:	/usr/include/stddef.h
time.o:	/usr/include/stdint.h
time.o:	/usr/include/stdio.h
time.o:	/usr/include/stdlib.h
time.o:	/usr/include/sys/cdefs.h
time.o:	/usr/include/sys/null.h
time.o:	/usr/include/sys/times.h
time.o:	/usr/include/sys/types.h
time.o:	/usr/include/sys/ucred.h
time.o:	/usr/include/sys/wait.h
time.o:	/usr/include/time.h
time.o:	/usr/include/unistd.h
time.o:	time.c
