
rshd.o:	/usr/include/ansi.h
rshd.o:	/usr/include/errno.h
rshd.o:	/usr/include/fcntl.h
rshd.o:	/usr/include/grp.h
rshd.o:	/usr/include/inttypes.h
rshd.o:	/usr/include/limits.h
rshd.o:	/usr/include/machine/interrupt.h
rshd.o:	/usr/include/minix/config.h
rshd.o:	/usr/include/minix/dir.h
rshd.o:	/usr/include/minix/ioctl.h
rshd.o:	/usr/include/minix/limits.h
rshd.o:	/usr/include/minix/sys_config.h
rshd.o:	/usr/include/minix/type.h
rshd.o:	/usr/include/minix/types.h
rshd.o:	/usr/include/net/gen/in.h
rshd.o:	/usr/include/net/gen/inet.h
rshd.o:	/usr/include/net/gen/netdb.h
rshd.o:	/usr/include/net/gen/socket.h
rshd.o:	/usr/include/net/gen/tcp.h
rshd.o:	/usr/include/net/gen/tcp_io.h
rshd.o:	/usr/include/net/hton.h
rshd.o:	/usr/include/net/ioctl.h
rshd.o:	/usr/include/net/netlib.h
rshd.o:	/usr/include/netinet/in.h
rshd.o:	/usr/include/pwd.h
rshd.o:	/usr/include/signal.h
rshd.o:	/usr/include/stddef.h
rshd.o:	/usr/include/stdint.h
rshd.o:	/usr/include/stdio.h
rshd.o:	/usr/include/stdlib.h
rshd.o:	/usr/include/string.h
rshd.o:	/usr/include/sys/cdefs.h
rshd.o:	/usr/include/sys/ioc_cmos.h
rshd.o:	/usr/include/sys/ioc_disk.h
rshd.o:	/usr/include/sys/ioc_file.h
rshd.o:	/usr/include/sys/ioc_memory.h
rshd.o:	/usr/include/sys/ioc_scsi.h
rshd.o:	/usr/include/sys/ioc_sound.h
rshd.o:	/usr/include/sys/ioc_tape.h
rshd.o:	/usr/include/sys/ioc_tty.h
rshd.o:	/usr/include/sys/ioctl.h
rshd.o:	/usr/include/sys/null.h
rshd.o:	/usr/include/sys/socket.h
rshd.o:	/usr/include/sys/types.h
rshd.o:	/usr/include/sys/ucred.h
rshd.o:	/usr/include/sys/un.h
rshd.o:	/usr/include/unistd.h
rshd.o:	rshd.c
