
readclock.o:	/usr/include/ansi.h
readclock.o:	/usr/include/errno.h
readclock.o:	/usr/include/limits.h
readclock.o:	/usr/include/machine/cmos.h
readclock.o:	/usr/include/machine/fpu.h
readclock.o:	/usr/include/machine/interrupt.h
readclock.o:	/usr/include/machine/mcontext.h
readclock.o:	/usr/include/machine/stackframe.h
readclock.o:	/usr/include/minix/com.h
readclock.o:	/usr/include/minix/config.h
readclock.o:	/usr/include/minix/const.h
readclock.o:	/usr/include/minix/devio.h
readclock.o:	/usr/include/minix/dir.h
readclock.o:	/usr/include/minix/endpoint.h
readclock.o:	/usr/include/minix/ioctl.h
readclock.o:	/usr/include/minix/ipc.h
readclock.o:	/usr/include/minix/ipcconst.h
readclock.o:	/usr/include/minix/limits.h
readclock.o:	/usr/include/minix/safecopies.h
readclock.o:	/usr/include/minix/sef.h
readclock.o:	/usr/include/minix/sys_config.h
readclock.o:	/usr/include/minix/syslib.h
readclock.o:	/usr/include/minix/sysutil.h
readclock.o:	/usr/include/minix/type.h
readclock.o:	/usr/include/minix/types.h
readclock.o:	/usr/include/minix/u64.h
readclock.o:	/usr/include/minix/vm.h
readclock.o:	/usr/include/stddef.h
readclock.o:	/usr/include/stdint.h
readclock.o:	/usr/include/stdio.h
readclock.o:	/usr/include/stdlib.h
readclock.o:	/usr/include/sys/cdefs.h
readclock.o:	/usr/include/sys/null.h
readclock.o:	/usr/include/sys/svrctl.h
readclock.o:	/usr/include/sys/types.h
readclock.o:	/usr/include/sys/ucred.h
readclock.o:	/usr/include/time.h
readclock.o:	/usr/include/unistd.h
readclock.o:	readclock.c
