
df.o:	/usr/include/ansi.h
df.o:	/usr/include/dirent.h
df.o:	/usr/include/errno.h
df.o:	/usr/include/fcntl.h
df.o:	/usr/include/limits.h
df.o:	/usr/include/machine/interrupt.h
df.o:	/usr/include/minix/config.h
df.o:	/usr/include/minix/const.h
df.o:	/usr/include/minix/dir.h
df.o:	/usr/include/minix/dirent.h
df.o:	/usr/include/minix/limits.h
df.o:	/usr/include/minix/minlib.h
df.o:	/usr/include/minix/sys_config.h
df.o:	/usr/include/minix/type.h
df.o:	/usr/include/minix/types.h
df.o:	/usr/include/stddef.h
df.o:	/usr/include/stdint.h
df.o:	/usr/include/stdio.h
df.o:	/usr/include/stdlib.h
df.o:	/usr/include/string.h
df.o:	/usr/include/sys/cdefs.h
df.o:	/usr/include/sys/null.h
df.o:	/usr/include/sys/stat.h
df.o:	/usr/include/sys/types.h
df.o:	/usr/include/sys/ucred.h
df.o:	/usr/include/unistd.h
df.o:	/usr/src/servers/mfs/const.h
df.o:	/usr/src/servers/mfs/super.h
df.o:	/usr/src/servers/mfs/type.h
df.o:	df.c
