
backup.o:	/usr/include/ansi.h
backup.o:	/usr/include/dirent.h
backup.o:	/usr/include/errno.h
backup.o:	/usr/include/fcntl.h
backup.o:	/usr/include/limits.h
backup.o:	/usr/include/machine/interrupt.h
backup.o:	/usr/include/minix/config.h
backup.o:	/usr/include/minix/dir.h
backup.o:	/usr/include/minix/dirent.h
backup.o:	/usr/include/minix/limits.h
backup.o:	/usr/include/minix/sys_config.h
backup.o:	/usr/include/minix/type.h
backup.o:	/usr/include/minix/types.h
backup.o:	/usr/include/stddef.h
backup.o:	/usr/include/stdint.h
backup.o:	/usr/include/stdio.h
backup.o:	/usr/include/stdlib.h
backup.o:	/usr/include/string.h
backup.o:	/usr/include/sys/cdefs.h
backup.o:	/usr/include/sys/null.h
backup.o:	/usr/include/sys/stat.h
backup.o:	/usr/include/sys/types.h
backup.o:	/usr/include/sys/ucred.h
backup.o:	/usr/include/sys/wait.h
backup.o:	/usr/include/unistd.h
backup.o:	/usr/include/utime.h
backup.o:	backup.c
