
autopart.o:	/usr/include/a.out.h
autopart.o:	/usr/include/ansi.h
autopart.o:	/usr/include/ctype.h
autopart.o:	/usr/include/dirent.h
autopart.o:	/usr/include/errno.h
autopart.o:	/usr/include/fcntl.h
autopart.o:	/usr/include/limits.h
autopart.o:	/usr/include/machine/interrupt.h
autopart.o:	/usr/include/machine/partition.h
autopart.o:	/usr/include/minix/a.out.h
autopart.o:	/usr/include/minix/com.h
autopart.o:	/usr/include/minix/config.h
autopart.o:	/usr/include/minix/const.h
autopart.o:	/usr/include/minix/dir.h
autopart.o:	/usr/include/minix/dirent.h
autopart.o:	/usr/include/minix/endpoint.h
autopart.o:	/usr/include/minix/ioctl.h
autopart.o:	/usr/include/minix/limits.h
autopart.o:	/usr/include/minix/partition.h
autopart.o:	/usr/include/minix/sys_config.h
autopart.o:	/usr/include/minix/sysinfo.h
autopart.o:	/usr/include/minix/type.h
autopart.o:	/usr/include/minix/types.h
autopart.o:	/usr/include/minix/u64.h
autopart.o:	/usr/include/net/ioctl.h
autopart.o:	/usr/include/signal.h
autopart.o:	/usr/include/stdarg.h
autopart.o:	/usr/include/stddef.h
autopart.o:	/usr/include/stdint.h
autopart.o:	/usr/include/stdio.h
autopart.o:	/usr/include/stdlib.h
autopart.o:	/usr/include/string.h
autopart.o:	/usr/include/sys/cdefs.h
autopart.o:	/usr/include/sys/ioc_cmos.h
autopart.o:	/usr/include/sys/ioc_disk.h
autopart.o:	/usr/include/sys/ioc_file.h
autopart.o:	/usr/include/sys/ioc_memory.h
autopart.o:	/usr/include/sys/ioc_scsi.h
autopart.o:	/usr/include/sys/ioc_sound.h
autopart.o:	/usr/include/sys/ioc_tape.h
autopart.o:	/usr/include/sys/ioc_tty.h
autopart.o:	/usr/include/sys/ioctl.h
autopart.o:	/usr/include/sys/null.h
autopart.o:	/usr/include/sys/stat.h
autopart.o:	/usr/include/sys/types.h
autopart.o:	/usr/include/sys/ucred.h
autopart.o:	/usr/include/sys/un.h
autopart.o:	/usr/include/sys/wait.h
autopart.o:	/usr/include/termcap.h
autopart.o:	/usr/include/termios.h
autopart.o:	/usr/include/time.h
autopart.o:	/usr/include/unistd.h
autopart.o:	autopart.c
