
host.o:	/usr/include/ansi.h
host.o:	/usr/include/assert.h
host.o:	/usr/include/errno.h
host.o:	/usr/include/fcntl.h
host.o:	/usr/include/inttypes.h
host.o:	/usr/include/limits.h
host.o:	/usr/include/machine/interrupt.h
host.o:	/usr/include/minix/config.h
host.o:	/usr/include/minix/dir.h
host.o:	/usr/include/minix/ioctl.h
host.o:	/usr/include/minix/limits.h
host.o:	/usr/include/minix/sys_config.h
host.o:	/usr/include/minix/type.h
host.o:	/usr/include/minix/types.h
host.o:	/usr/include/net/gen/in.h
host.o:	/usr/include/net/gen/inet.h
host.o:	/usr/include/net/gen/nameser.h
host.o:	/usr/include/net/gen/netdb.h
host.o:	/usr/include/net/gen/resolv.h
host.o:	/usr/include/net/gen/socket.h
host.o:	/usr/include/net/gen/tcp.h
host.o:	/usr/include/net/gen/tcp_io.h
host.o:	/usr/include/net/hton.h
host.o:	/usr/include/net/ioctl.h
host.o:	/usr/include/net/netlib.h
host.o:	/usr/include/netinet/in.h
host.o:	/usr/include/stddef.h
host.o:	/usr/include/stdint.h
host.o:	/usr/include/stdio.h
host.o:	/usr/include/stdlib.h
host.o:	/usr/include/string.h
host.o:	/usr/include/sys/cdefs.h
host.o:	/usr/include/sys/ioc_cmos.h
host.o:	/usr/include/sys/ioc_disk.h
host.o:	/usr/include/sys/ioc_file.h
host.o:	/usr/include/sys/ioc_memory.h
host.o:	/usr/include/sys/ioc_scsi.h
host.o:	/usr/include/sys/ioc_sound.h
host.o:	/usr/include/sys/ioc_tape.h
host.o:	/usr/include/sys/ioc_tty.h
host.o:	/usr/include/sys/ioctl.h
host.o:	/usr/include/sys/null.h
host.o:	/usr/include/sys/socket.h
host.o:	/usr/include/sys/types.h
host.o:	/usr/include/sys/ucred.h
host.o:	/usr/include/sys/un.h
host.o:	/usr/include/unistd.h
host.o:	host.c
