
ping.o:	/usr/include/ansi.h
ping.o:	/usr/include/errno.h
ping.o:	/usr/include/fcntl.h
ping.o:	/usr/include/inttypes.h
ping.o:	/usr/include/limits.h
ping.o:	/usr/include/machine/interrupt.h
ping.o:	/usr/include/minix/config.h
ping.o:	/usr/include/minix/dir.h
ping.o:	/usr/include/minix/ioctl.h
ping.o:	/usr/include/minix/limits.h
ping.o:	/usr/include/minix/sys_config.h
ping.o:	/usr/include/minix/type.h
ping.o:	/usr/include/minix/types.h
ping.o:	/usr/include/net/gen/icmp_hdr.h
ping.o:	/usr/include/net/gen/in.h
ping.o:	/usr/include/net/gen/inet.h
ping.o:	/usr/include/net/gen/ip_hdr.h
ping.o:	/usr/include/net/gen/ip_io.h
ping.o:	/usr/include/net/gen/netdb.h
ping.o:	/usr/include/net/gen/oneCsum.h
ping.o:	/usr/include/net/gen/socket.h
ping.o:	/usr/include/net/ioctl.h
ping.o:	/usr/include/netinet/in.h
ping.o:	/usr/include/signal.h
ping.o:	/usr/include/stddef.h
ping.o:	/usr/include/stdint.h
ping.o:	/usr/include/stdio.h
ping.o:	/usr/include/stdlib.h
ping.o:	/usr/include/string.h
ping.o:	/usr/include/sys/cdefs.h
ping.o:	/usr/include/sys/ioc_cmos.h
ping.o:	/usr/include/sys/ioc_disk.h
ping.o:	/usr/include/sys/ioc_file.h
ping.o:	/usr/include/sys/ioc_memory.h
ping.o:	/usr/include/sys/ioc_scsi.h
ping.o:	/usr/include/sys/ioc_sound.h
ping.o:	/usr/include/sys/ioc_tape.h
ping.o:	/usr/include/sys/ioc_tty.h
ping.o:	/usr/include/sys/ioctl.h
ping.o:	/usr/include/sys/null.h
ping.o:	/usr/include/sys/socket.h
ping.o:	/usr/include/sys/types.h
ping.o:	/usr/include/sys/ucred.h
ping.o:	/usr/include/sys/un.h
ping.o:	/usr/include/unistd.h
ping.o:	ping.c
