
rsh.o:	/usr/include/ansi.h
rsh.o:	/usr/include/errno.h
rsh.o:	/usr/include/inttypes.h
rsh.o:	/usr/include/limits.h
rsh.o:	/usr/include/machine/interrupt.h
rsh.o:	/usr/include/minix/config.h
rsh.o:	/usr/include/minix/dir.h
rsh.o:	/usr/include/minix/ioctl.h
rsh.o:	/usr/include/minix/limits.h
rsh.o:	/usr/include/minix/sys_config.h
rsh.o:	/usr/include/minix/type.h
rsh.o:	/usr/include/minix/types.h
rsh.o:	/usr/include/net/gen/netdb.h
rsh.o:	/usr/include/net/gen/socket.h
rsh.o:	/usr/include/net/ioctl.h
rsh.o:	/usr/include/net/netlib.h
rsh.o:	/usr/include/netinet/in.h
rsh.o:	/usr/include/pwd.h
rsh.o:	/usr/include/signal.h
rsh.o:	/usr/include/stddef.h
rsh.o:	/usr/include/stdint.h
rsh.o:	/usr/include/stdio.h
rsh.o:	/usr/include/stdlib.h
rsh.o:	/usr/include/string.h
rsh.o:	/usr/include/sys/cdefs.h
rsh.o:	/usr/include/sys/ioc_cmos.h
rsh.o:	/usr/include/sys/ioc_disk.h
rsh.o:	/usr/include/sys/ioc_file.h
rsh.o:	/usr/include/sys/ioc_memory.h
rsh.o:	/usr/include/sys/ioc_scsi.h
rsh.o:	/usr/include/sys/ioc_sound.h
rsh.o:	/usr/include/sys/ioc_tape.h
rsh.o:	/usr/include/sys/ioc_tty.h
rsh.o:	/usr/include/sys/ioctl.h
rsh.o:	/usr/include/sys/null.h
rsh.o:	/usr/include/sys/socket.h
rsh.o:	/usr/include/sys/types.h
rsh.o:	/usr/include/sys/ucred.h
rsh.o:	/usr/include/sys/un.h
rsh.o:	/usr/include/unistd.h
rsh.o:	rsh.c
