
arp.o:	/usr/include/ansi.h
arp.o:	/usr/include/errno.h
arp.o:	/usr/include/fcntl.h
arp.o:	/usr/include/inttypes.h
arp.o:	/usr/include/limits.h
arp.o:	/usr/include/machine/interrupt.h
arp.o:	/usr/include/minix/config.h
arp.o:	/usr/include/minix/dir.h
arp.o:	/usr/include/minix/ioctl.h
arp.o:	/usr/include/minix/limits.h
arp.o:	/usr/include/minix/sys_config.h
arp.o:	/usr/include/minix/type.h
arp.o:	/usr/include/minix/types.h
arp.o:	/usr/include/net/gen/arp_io.h
arp.o:	/usr/include/net/gen/ether.h
arp.o:	/usr/include/net/gen/if_ether.h
arp.o:	/usr/include/net/gen/in.h
arp.o:	/usr/include/net/gen/inet.h
arp.o:	/usr/include/net/gen/ip_io.h
arp.o:	/usr/include/net/gen/netdb.h
arp.o:	/usr/include/net/gen/socket.h
arp.o:	/usr/include/net/ioctl.h
arp.o:	/usr/include/net/netlib.h
arp.o:	/usr/include/netinet/in.h
arp.o:	/usr/include/stdarg.h
arp.o:	/usr/include/stddef.h
arp.o:	/usr/include/stdint.h
arp.o:	/usr/include/stdio.h
arp.o:	/usr/include/stdlib.h
arp.o:	/usr/include/string.h
arp.o:	/usr/include/sys/cdefs.h
arp.o:	/usr/include/sys/ioc_cmos.h
arp.o:	/usr/include/sys/ioc_disk.h
arp.o:	/usr/include/sys/ioc_file.h
arp.o:	/usr/include/sys/ioc_memory.h
arp.o:	/usr/include/sys/ioc_scsi.h
arp.o:	/usr/include/sys/ioc_sound.h
arp.o:	/usr/include/sys/ioc_tape.h
arp.o:	/usr/include/sys/ioc_tty.h
arp.o:	/usr/include/sys/ioctl.h
arp.o:	/usr/include/sys/null.h
arp.o:	/usr/include/sys/socket.h
arp.o:	/usr/include/sys/ucred.h
arp.o:	/usr/include/sys/un.h
arp.o:	/usr/include/unistd.h
arp.o:	arp.c
