
rarpd.o:	/usr/include/ansi.h
rarpd.o:	/usr/include/errno.h
rarpd.o:	/usr/include/fcntl.h
rarpd.o:	/usr/include/inttypes.h
rarpd.o:	/usr/include/limits.h
rarpd.o:	/usr/include/machine/interrupt.h
rarpd.o:	/usr/include/minix/config.h
rarpd.o:	/usr/include/minix/dir.h
rarpd.o:	/usr/include/minix/ioctl.h
rarpd.o:	/usr/include/minix/limits.h
rarpd.o:	/usr/include/minix/sys_config.h
rarpd.o:	/usr/include/minix/type.h
rarpd.o:	/usr/include/minix/types.h
rarpd.o:	/usr/include/net/gen/eth_io.h
rarpd.o:	/usr/include/net/gen/ether.h
rarpd.o:	/usr/include/net/gen/if_ether.h
rarpd.o:	/usr/include/net/gen/in.h
rarpd.o:	/usr/include/net/gen/inet.h
rarpd.o:	/usr/include/net/gen/ip_io.h
rarpd.o:	/usr/include/net/gen/nameser.h
rarpd.o:	/usr/include/net/gen/netdb.h
rarpd.o:	/usr/include/net/gen/socket.h
rarpd.o:	/usr/include/net/hton.h
rarpd.o:	/usr/include/net/ioctl.h
rarpd.o:	/usr/include/netinet/in.h
rarpd.o:	/usr/include/signal.h
rarpd.o:	/usr/include/stddef.h
rarpd.o:	/usr/include/stdint.h
rarpd.o:	/usr/include/stdio.h
rarpd.o:	/usr/include/stdlib.h
rarpd.o:	/usr/include/string.h
rarpd.o:	/usr/include/sys/asynchio.h
rarpd.o:	/usr/include/sys/cdefs.h
rarpd.o:	/usr/include/sys/ioc_cmos.h
rarpd.o:	/usr/include/sys/ioc_disk.h
rarpd.o:	/usr/include/sys/ioc_file.h
rarpd.o:	/usr/include/sys/ioc_memory.h
rarpd.o:	/usr/include/sys/ioc_scsi.h
rarpd.o:	/usr/include/sys/ioc_sound.h
rarpd.o:	/usr/include/sys/ioc_tape.h
rarpd.o:	/usr/include/sys/ioc_tty.h
rarpd.o:	/usr/include/sys/ioctl.h
rarpd.o:	/usr/include/sys/null.h
rarpd.o:	/usr/include/sys/select.h
rarpd.o:	/usr/include/sys/socket.h
rarpd.o:	/usr/include/sys/time.h
rarpd.o:	/usr/include/sys/types.h
rarpd.o:	/usr/include/sys/ucred.h
rarpd.o:	/usr/include/sys/un.h
rarpd.o:	/usr/include/unistd.h
rarpd.o:	rarpd.c
