
atl2.o:	/usr/include/ansi.h
atl2.o:	/usr/include/assert.h
atl2.o:	/usr/include/errno.h
atl2.o:	/usr/include/limits.h
atl2.o:	/usr/include/machine/bios.h
atl2.o:	/usr/include/machine/fpu.h
atl2.o:	/usr/include/machine/interrupt.h
atl2.o:	/usr/include/machine/mcontext.h
atl2.o:	/usr/include/machine/pci.h
atl2.o:	/usr/include/machine/ports.h
atl2.o:	/usr/include/machine/stackframe.h
atl2.o:	/usr/include/minix/bitmap.h
atl2.o:	/usr/include/minix/callnr.h
atl2.o:	/usr/include/minix/com.h
atl2.o:	/usr/include/minix/config.h
atl2.o:	/usr/include/minix/const.h
atl2.o:	/usr/include/minix/devio.h
atl2.o:	/usr/include/minix/dir.h
atl2.o:	/usr/include/minix/dmap.h
atl2.o:	/usr/include/minix/drivers.h
atl2.o:	/usr/include/minix/ds.h
atl2.o:	/usr/include/minix/endpoint.h
atl2.o:	/usr/include/minix/ipc.h
atl2.o:	/usr/include/minix/ipcconst.h
atl2.o:	/usr/include/minix/limits.h
atl2.o:	/usr/include/minix/netdriver.h
atl2.o:	/usr/include/minix/safecopies.h
atl2.o:	/usr/include/minix/sef.h
atl2.o:	/usr/include/minix/spin.h
atl2.o:	/usr/include/minix/sys_config.h
atl2.o:	/usr/include/minix/syslib.h
atl2.o:	/usr/include/minix/sysutil.h
atl2.o:	/usr/include/minix/timers.h
atl2.o:	/usr/include/minix/type.h
atl2.o:	/usr/include/minix/types.h
atl2.o:	/usr/include/minix/u64.h
atl2.o:	/usr/include/minix/vm.h
atl2.o:	/usr/include/net/gen/eth_io.h
atl2.o:	/usr/include/net/gen/ether.h
atl2.o:	/usr/include/signal.h
atl2.o:	/usr/include/stddef.h
atl2.o:	/usr/include/stdint.h
atl2.o:	/usr/include/stdio.h
atl2.o:	/usr/include/stdlib.h
atl2.o:	/usr/include/string.h
atl2.o:	/usr/include/sys/cdefs.h
atl2.o:	/usr/include/sys/mman.h
atl2.o:	/usr/include/sys/null.h
atl2.o:	/usr/include/sys/param.h
atl2.o:	/usr/include/sys/types.h
atl2.o:	/usr/include/sys/ucred.h
atl2.o:	/usr/include/timers.h
atl2.o:	/usr/include/unistd.h
atl2.o:	atl2.c
atl2.o:	atl2.h
