
login.o:	/usr/include/ansi.h
login.o:	/usr/include/errno.h
login.o:	/usr/include/fcntl.h
login.o:	/usr/include/grp.h
login.o:	/usr/include/limits.h
login.o:	/usr/include/machine/interrupt.h
login.o:	/usr/include/minix/config.h
login.o:	/usr/include/minix/dir.h
login.o:	/usr/include/minix/limits.h
login.o:	/usr/include/minix/minlib.h
login.o:	/usr/include/minix/paths.h
login.o:	/usr/include/minix/sys_config.h
login.o:	/usr/include/minix/type.h
login.o:	/usr/include/minix/types.h
login.o:	/usr/include/pwd.h
login.o:	/usr/include/signal.h
login.o:	/usr/include/stddef.h
login.o:	/usr/include/stdint.h
login.o:	/usr/include/stdio.h
login.o:	/usr/include/stdlib.h
login.o:	/usr/include/string.h
login.o:	/usr/include/sys/cdefs.h
login.o:	/usr/include/sys/null.h
login.o:	/usr/include/sys/stat.h
login.o:	/usr/include/sys/types.h
login.o:	/usr/include/sys/ucred.h
login.o:	/usr/include/sys/utsname.h
login.o:	/usr/include/time.h
login.o:	/usr/include/ttyent.h
login.o:	/usr/include/unistd.h
login.o:	/usr/include/utmp.h
login.o:	login.c
