
writeisofs.o:	/usr/include/a.out.h
writeisofs.o:	/usr/include/ansi.h
writeisofs.o:	/usr/include/assert.h
writeisofs.o:	/usr/include/ctype.h
writeisofs.o:	/usr/include/dirent.h
writeisofs.o:	/usr/include/errno.h
writeisofs.o:	/usr/include/fcntl.h
writeisofs.o:	/usr/include/limits.h
writeisofs.o:	/usr/include/machine/interrupt.h
writeisofs.o:	/usr/include/machine/partition.h
writeisofs.o:	/usr/include/minix/a.out.h
writeisofs.o:	/usr/include/minix/config.h
writeisofs.o:	/usr/include/minix/dir.h
writeisofs.o:	/usr/include/minix/dirent.h
writeisofs.o:	/usr/include/minix/limits.h
writeisofs.o:	/usr/include/minix/sys_config.h
writeisofs.o:	/usr/include/minix/type.h
writeisofs.o:	/usr/include/minix/types.h
writeisofs.o:	/usr/include/stddef.h
writeisofs.o:	/usr/include/stdint.h
writeisofs.o:	/usr/include/stdio.h
writeisofs.o:	/usr/include/stdlib.h
writeisofs.o:	/usr/include/string.h
writeisofs.o:	/usr/include/sys/cdefs.h
writeisofs.o:	/usr/include/sys/null.h
writeisofs.o:	/usr/include/sys/stat.h
writeisofs.o:	/usr/include/sys/types.h
writeisofs.o:	/usr/include/sys/ucred.h
writeisofs.o:	/usr/include/time.h
writeisofs.o:	/usr/include/unistd.h
writeisofs.o:	writeisofs.c
