
at.o:	/usr/include/ansi.h
at.o:	/usr/include/errno.h
at.o:	/usr/include/fcntl.h
at.o:	/usr/include/limits.h
at.o:	/usr/include/machine/interrupt.h
at.o:	/usr/include/minix/config.h
at.o:	/usr/include/minix/dir.h
at.o:	/usr/include/minix/limits.h
at.o:	/usr/include/minix/sys_config.h
at.o:	/usr/include/minix/type.h
at.o:	/usr/include/minix/types.h
at.o:	/usr/include/signal.h
at.o:	/usr/include/stddef.h
at.o:	/usr/include/stdint.h
at.o:	/usr/include/stdio.h
at.o:	/usr/include/stdlib.h
at.o:	/usr/include/string.h
at.o:	/usr/include/sys/cdefs.h
at.o:	/usr/include/sys/null.h
at.o:	/usr/include/sys/stat.h
at.o:	/usr/include/sys/types.h
at.o:	/usr/include/sys/ucred.h
at.o:	/usr/include/time.h
at.o:	/usr/include/unistd.h
at.o:	at.c
