
ifdef.o:	/usr/include/ansi.h
ifdef.o:	/usr/include/limits.h
ifdef.o:	/usr/include/machine/interrupt.h
ifdef.o:	/usr/include/minix/config.h
ifdef.o:	/usr/include/minix/dir.h
ifdef.o:	/usr/include/minix/limits.h
ifdef.o:	/usr/include/minix/sys_config.h
ifdef.o:	/usr/include/minix/type.h
ifdef.o:	/usr/include/minix/types.h
ifdef.o:	/usr/include/stddef.h
ifdef.o:	/usr/include/stdint.h
ifdef.o:	/usr/include/stdio.h
ifdef.o:	/usr/include/stdlib.h
ifdef.o:	/usr/include/string.h
ifdef.o:	/usr/include/sys/cdefs.h
ifdef.o:	/usr/include/sys/null.h
ifdef.o:	/usr/include/sys/types.h
ifdef.o:	/usr/include/sys/ucred.h
ifdef.o:	/usr/include/unistd.h
ifdef.o:	ifdef.c
