
atnormalize.o:	/usr/include/a.out.h
atnormalize.o:	/usr/include/ansi.h
atnormalize.o:	/usr/include/ctype.h
atnormalize.o:	/usr/include/dirent.h
atnormalize.o:	/usr/include/errno.h
atnormalize.o:	/usr/include/fcntl.h
atnormalize.o:	/usr/include/limits.h
atnormalize.o:	/usr/include/machine/interrupt.h
atnormalize.o:	/usr/include/machine/partition.h
atnormalize.o:	/usr/include/minix/a.out.h
atnormalize.o:	/usr/include/minix/config.h
atnormalize.o:	/usr/include/minix/const.h
atnormalize.o:	/usr/include/minix/dir.h
atnormalize.o:	/usr/include/minix/dirent.h
atnormalize.o:	/usr/include/minix/ioctl.h
atnormalize.o:	/usr/include/minix/limits.h
atnormalize.o:	/usr/include/minix/partition.h
atnormalize.o:	/usr/include/minix/sys_config.h
atnormalize.o:	/usr/include/minix/type.h
atnormalize.o:	/usr/include/minix/types.h
atnormalize.o:	/usr/include/minix/u64.h
atnormalize.o:	/usr/include/net/ioctl.h
atnormalize.o:	/usr/include/signal.h
atnormalize.o:	/usr/include/stdarg.h
atnormalize.o:	/usr/include/stddef.h
atnormalize.o:	/usr/include/stdint.h
atnormalize.o:	/usr/include/stdio.h
atnormalize.o:	/usr/include/stdlib.h
atnormalize.o:	/usr/include/string.h
atnormalize.o:	/usr/include/sys/cdefs.h
atnormalize.o:	/usr/include/sys/ioc_cmos.h
atnormalize.o:	/usr/include/sys/ioc_disk.h
atnormalize.o:	/usr/include/sys/ioc_file.h
atnormalize.o:	/usr/include/sys/ioc_memory.h
atnormalize.o:	/usr/include/sys/ioc_scsi.h
atnormalize.o:	/usr/include/sys/ioc_sound.h
atnormalize.o:	/usr/include/sys/ioc_tape.h
atnormalize.o:	/usr/include/sys/ioc_tty.h
atnormalize.o:	/usr/include/sys/ioctl.h
atnormalize.o:	/usr/include/sys/null.h
atnormalize.o:	/usr/include/sys/stat.h
atnormalize.o:	/usr/include/sys/types.h
atnormalize.o:	/usr/include/sys/ucred.h
atnormalize.o:	/usr/include/sys/un.h
atnormalize.o:	/usr/include/sys/wait.h
atnormalize.o:	/usr/include/termcap.h
atnormalize.o:	/usr/include/termios.h
atnormalize.o:	/usr/include/time.h
atnormalize.o:	/usr/include/unistd.h
atnormalize.o:	atnormalize.c
