
hello.o:	/usr/include/ansi.h
hello.o:	/usr/include/errno.h
hello.o:	/usr/include/limits.h
hello.o:	/usr/include/machine/bios.h
hello.o:	/usr/include/machine/fpu.h
hello.o:	/usr/include/machine/interrupt.h
hello.o:	/usr/include/machine/mcontext.h
hello.o:	/usr/include/machine/ports.h
hello.o:	/usr/include/machine/stackframe.h
hello.o:	/usr/include/minix/bitmap.h
hello.o:	/usr/include/minix/callnr.h
hello.o:	/usr/include/minix/com.h
hello.o:	/usr/include/minix/config.h
hello.o:	/usr/include/minix/const.h
hello.o:	/usr/include/minix/devio.h
hello.o:	/usr/include/minix/dir.h
hello.o:	/usr/include/minix/dmap.h
hello.o:	/usr/include/minix/driver.h
hello.o:	/usr/include/minix/drivers.h
hello.o:	/usr/include/minix/ds.h
hello.o:	/usr/include/minix/endpoint.h
hello.o:	/usr/include/minix/ipc.h
hello.o:	/usr/include/minix/ipcconst.h
hello.o:	/usr/include/minix/limits.h
hello.o:	/usr/include/minix/partition.h
hello.o:	/usr/include/minix/safecopies.h
hello.o:	/usr/include/minix/sef.h
hello.o:	/usr/include/minix/spin.h
hello.o:	/usr/include/minix/sys_config.h
hello.o:	/usr/include/minix/syslib.h
hello.o:	/usr/include/minix/sysutil.h
hello.o:	/usr/include/minix/timers.h
hello.o:	/usr/include/minix/type.h
hello.o:	/usr/include/minix/types.h
hello.o:	/usr/include/minix/u64.h
hello.o:	/usr/include/minix/vm.h
hello.o:	/usr/include/signal.h
hello.o:	/usr/include/stddef.h
hello.o:	/usr/include/stdint.h
hello.o:	/usr/include/stdio.h
hello.o:	/usr/include/stdlib.h
hello.o:	/usr/include/string.h
hello.o:	/usr/include/sys/cdefs.h
hello.o:	/usr/include/sys/null.h
hello.o:	/usr/include/sys/param.h
hello.o:	/usr/include/sys/types.h
hello.o:	/usr/include/sys/ucred.h
hello.o:	/usr/include/timers.h
hello.o:	/usr/include/unistd.h
hello.o:	hello.c
hello.o:	hello.h
