
xargs.o:	/usr/include/ansi.h
xargs.o:	/usr/include/errno.h
xargs.o:	/usr/include/fcntl.h
xargs.o:	/usr/include/limits.h
xargs.o:	/usr/include/machine/interrupt.h
xargs.o:	/usr/include/minix/config.h
xargs.o:	/usr/include/minix/dir.h
xargs.o:	/usr/include/minix/limits.h
xargs.o:	/usr/include/minix/sys_config.h
xargs.o:	/usr/include/minix/type.h
xargs.o:	/usr/include/minix/types.h
xargs.o:	/usr/include/stdarg.h
xargs.o:	/usr/include/stddef.h
xargs.o:	/usr/include/stdint.h
xargs.o:	/usr/include/stdio.h
xargs.o:	/usr/include/stdlib.h
xargs.o:	/usr/include/string.h
xargs.o:	/usr/include/sys/cdefs.h
xargs.o:	/usr/include/sys/null.h
xargs.o:	/usr/include/sys/types.h
xargs.o:	/usr/include/sys/ucred.h
xargs.o:	/usr/include/sys/wait.h
xargs.o:	/usr/include/unistd.h
xargs.o:	xargs.c
