
cut.o:	/usr/include/ansi.h
cut.o:	/usr/include/ctype.h
cut.o:	/usr/include/err.h
cut.o:	/usr/include/errno.h
cut.o:	/usr/include/limits.h
cut.o:	/usr/include/locale.h
cut.o:	/usr/include/machine/interrupt.h
cut.o:	/usr/include/minix/config.h
cut.o:	/usr/include/minix/dir.h
cut.o:	/usr/include/minix/limits.h
cut.o:	/usr/include/minix/sys_config.h
cut.o:	/usr/include/minix/type.h
cut.o:	/usr/include/minix/types.h
cut.o:	/usr/include/pwd.h
cut.o:	/usr/include/stdarg.h
cut.o:	/usr/include/stddef.h
cut.o:	/usr/include/stdint.h
cut.o:	/usr/include/stdio.h
cut.o:	/usr/include/stdlib.h
cut.o:	/usr/include/string.h
cut.o:	/usr/include/sys/cdefs.h
cut.o:	/usr/include/sys/null.h
cut.o:	/usr/include/sys/param.h
cut.o:	/usr/include/sys/types.h
cut.o:	/usr/include/sys/ucred.h
cut.o:	/usr/include/termios.h
cut.o:	/usr/include/unistd.h
cut.o:	/usr/include/util.h
cut.o:	/usr/include/utmp.h
cut.o:	/usr/include/wchar.h
cut.o:	cut.c
cut.o:	x_cut.c
