
stat.o:	/usr/include/ansi.h
stat.o:	/usr/include/errno.h
stat.o:	/usr/include/limits.h
stat.o:	/usr/include/machine/interrupt.h
stat.o:	/usr/include/minix/config.h
stat.o:	/usr/include/minix/dir.h
stat.o:	/usr/include/minix/limits.h
stat.o:	/usr/include/minix/sys_config.h
stat.o:	/usr/include/minix/type.h
stat.o:	/usr/include/minix/types.h
stat.o:	/usr/include/stddef.h
stat.o:	/usr/include/stdint.h
stat.o:	/usr/include/stdio.h
stat.o:	/usr/include/stdlib.h
stat.o:	/usr/include/string.h
stat.o:	/usr/include/sys/cdefs.h
stat.o:	/usr/include/sys/null.h
stat.o:	/usr/include/sys/stat.h
stat.o:	/usr/include/sys/types.h
stat.o:	/usr/include/sys/ucred.h
stat.o:	/usr/include/time.h
stat.o:	/usr/include/unistd.h
stat.o:	stat.c
