
amddev.o:	/usr/include/ansi.h
amddev.o:	/usr/include/errno.h
amddev.o:	/usr/include/limits.h
amddev.o:	/usr/include/machine/fpu.h
amddev.o:	/usr/include/machine/interrupt.h
amddev.o:	/usr/include/machine/mcontext.h
amddev.o:	/usr/include/machine/pci.h
amddev.o:	/usr/include/machine/stackframe.h
amddev.o:	/usr/include/machine/vm.h
amddev.o:	/usr/include/minix/callnr.h
amddev.o:	/usr/include/minix/com.h
amddev.o:	/usr/include/minix/config.h
amddev.o:	/usr/include/minix/const.h
amddev.o:	/usr/include/minix/devio.h
amddev.o:	/usr/include/minix/dir.h
amddev.o:	/usr/include/minix/driver.h
amddev.o:	/usr/include/minix/endpoint.h
amddev.o:	/usr/include/minix/ipc.h
amddev.o:	/usr/include/minix/ipcconst.h
amddev.o:	/usr/include/minix/limits.h
amddev.o:	/usr/include/minix/partition.h
amddev.o:	/usr/include/minix/safecopies.h
amddev.o:	/usr/include/minix/sef.h
amddev.o:	/usr/include/minix/sys_config.h
amddev.o:	/usr/include/minix/syslib.h
amddev.o:	/usr/include/minix/sysutil.h
amddev.o:	/usr/include/minix/type.h
amddev.o:	/usr/include/minix/types.h
amddev.o:	/usr/include/minix/u64.h
amddev.o:	/usr/include/minix/vm.h
amddev.o:	/usr/include/signal.h
amddev.o:	/usr/include/stddef.h
amddev.o:	/usr/include/stdint.h
amddev.o:	/usr/include/stdio.h
amddev.o:	/usr/include/stdlib.h
amddev.o:	/usr/include/string.h
amddev.o:	/usr/include/sys/cdefs.h
amddev.o:	/usr/include/sys/null.h
amddev.o:	/usr/include/sys/param.h
amddev.o:	/usr/include/sys/types.h
amddev.o:	/usr/include/sys/ucred.h
amddev.o:	/usr/include/unistd.h
amddev.o:	amddev.c
