
su.o:	/usr/include/ansi.h
su.o:	/usr/include/fcntl.h
su.o:	/usr/include/grp.h
su.o:	/usr/include/limits.h
su.o:	/usr/include/machine/interrupt.h
su.o:	/usr/include/minix/config.h
su.o:	/usr/include/minix/dir.h
su.o:	/usr/include/minix/limits.h
su.o:	/usr/include/minix/minlib.h
su.o:	/usr/include/minix/sys_config.h
su.o:	/usr/include/minix/type.h
su.o:	/usr/include/minix/types.h
su.o:	/usr/include/pwd.h
su.o:	/usr/include/stddef.h
su.o:	/usr/include/stdint.h
su.o:	/usr/include/stdio.h
su.o:	/usr/include/stdlib.h
su.o:	/usr/include/string.h
su.o:	/usr/include/sys/cdefs.h
su.o:	/usr/include/sys/null.h
su.o:	/usr/include/sys/types.h
su.o:	/usr/include/sys/ucred.h
su.o:	/usr/include/time.h
su.o:	/usr/include/unistd.h
su.o:	su.c
