
chown.o:	/usr/include/ansi.h
chown.o:	/usr/include/ctype.h
chown.o:	/usr/include/dirent.h
chown.o:	/usr/include/errno.h
chown.o:	/usr/include/grp.h
chown.o:	/usr/include/limits.h
chown.o:	/usr/include/machine/interrupt.h
chown.o:	/usr/include/minix/config.h
chown.o:	/usr/include/minix/dir.h
chown.o:	/usr/include/minix/dirent.h
chown.o:	/usr/include/minix/limits.h
chown.o:	/usr/include/minix/minlib.h
chown.o:	/usr/include/minix/sys_config.h
chown.o:	/usr/include/minix/type.h
chown.o:	/usr/include/minix/types.h
chown.o:	/usr/include/pwd.h
chown.o:	/usr/include/stddef.h
chown.o:	/usr/include/stdint.h
chown.o:	/usr/include/stdio.h
chown.o:	/usr/include/stdlib.h
chown.o:	/usr/include/string.h
chown.o:	/usr/include/sys/cdefs.h
chown.o:	/usr/include/sys/null.h
chown.o:	/usr/include/sys/stat.h
chown.o:	/usr/include/sys/types.h
chown.o:	/usr/include/sys/ucred.h
chown.o:	/usr/include/unistd.h
chown.o:	chown.c
