
lance.o:	/usr/include/ansi.h
lance.o:	/usr/include/assert.h
lance.o:	/usr/include/errno.h
lance.o:	/usr/include/limits.h
lance.o:	/usr/include/machine/bios.h
lance.o:	/usr/include/machine/fpu.h
lance.o:	/usr/include/machine/interrupt.h
lance.o:	/usr/include/machine/mcontext.h
lance.o:	/usr/include/machine/pci.h
lance.o:	/usr/include/machine/ports.h
lance.o:	/usr/include/machine/stackframe.h
lance.o:	/usr/include/minix/bitmap.h
lance.o:	/usr/include/minix/callnr.h
lance.o:	/usr/include/minix/com.h
lance.o:	/usr/include/minix/config.h
lance.o:	/usr/include/minix/const.h
lance.o:	/usr/include/minix/devio.h
lance.o:	/usr/include/minix/dir.h
lance.o:	/usr/include/minix/dmap.h
lance.o:	/usr/include/minix/drivers.h
lance.o:	/usr/include/minix/ds.h
lance.o:	/usr/include/minix/endpoint.h
lance.o:	/usr/include/minix/ipc.h
lance.o:	/usr/include/minix/ipcconst.h
lance.o:	/usr/include/minix/limits.h
lance.o:	/usr/include/minix/netdriver.h
lance.o:	/usr/include/minix/safecopies.h
lance.o:	/usr/include/minix/sef.h
lance.o:	/usr/include/minix/spin.h
lance.o:	/usr/include/minix/sys_config.h
lance.o:	/usr/include/minix/syslib.h
lance.o:	/usr/include/minix/sysutil.h
lance.o:	/usr/include/minix/timers.h
lance.o:	/usr/include/minix/type.h
lance.o:	/usr/include/minix/types.h
lance.o:	/usr/include/minix/u64.h
lance.o:	/usr/include/minix/vm.h
lance.o:	/usr/include/net/gen/eth_io.h
lance.o:	/usr/include/net/gen/ether.h
lance.o:	/usr/include/net/hton.h
lance.o:	/usr/include/signal.h
lance.o:	/usr/include/stddef.h
lance.o:	/usr/include/stdint.h
lance.o:	/usr/include/stdio.h
lance.o:	/usr/include/stdlib.h
lance.o:	/usr/include/string.h
lance.o:	/usr/include/sys/cdefs.h
lance.o:	/usr/include/sys/null.h
lance.o:	/usr/include/sys/param.h
lance.o:	/usr/include/sys/types.h
lance.o:	/usr/include/sys/ucred.h
lance.o:	/usr/include/timers.h
lance.o:	/usr/include/unistd.h
lance.o:	lance.c
lance.o:	lance.h
