
add_route.o:	/usr/include/ansi.h
add_route.o:	/usr/include/errno.h
add_route.o:	/usr/include/fcntl.h
add_route.o:	/usr/include/inttypes.h
add_route.o:	/usr/include/limits.h
add_route.o:	/usr/include/machine/interrupt.h
add_route.o:	/usr/include/minix/config.h
add_route.o:	/usr/include/minix/dir.h
add_route.o:	/usr/include/minix/ioctl.h
add_route.o:	/usr/include/minix/limits.h
add_route.o:	/usr/include/minix/sys_config.h
add_route.o:	/usr/include/minix/type.h
add_route.o:	/usr/include/minix/types.h
add_route.o:	/usr/include/net/gen/in.h
add_route.o:	/usr/include/net/gen/inet.h
add_route.o:	/usr/include/net/gen/ip_io.h
add_route.o:	/usr/include/net/gen/netdb.h
add_route.o:	/usr/include/net/gen/route.h
add_route.o:	/usr/include/net/gen/socket.h
add_route.o:	/usr/include/net/hton.h
add_route.o:	/usr/include/net/ioctl.h
add_route.o:	/usr/include/net/netlib.h
add_route.o:	/usr/include/netinet/in.h
add_route.o:	/usr/include/stddef.h
add_route.o:	/usr/include/stdint.h
add_route.o:	/usr/include/stdio.h
add_route.o:	/usr/include/stdlib.h
add_route.o:	/usr/include/string.h
add_route.o:	/usr/include/sys/cdefs.h
add_route.o:	/usr/include/sys/ioc_cmos.h
add_route.o:	/usr/include/sys/ioc_disk.h
add_route.o:	/usr/include/sys/ioc_file.h
add_route.o:	/usr/include/sys/ioc_memory.h
add_route.o:	/usr/include/sys/ioc_scsi.h
add_route.o:	/usr/include/sys/ioc_sound.h
add_route.o:	/usr/include/sys/ioc_tape.h
add_route.o:	/usr/include/sys/ioc_tty.h
add_route.o:	/usr/include/sys/ioctl.h
add_route.o:	/usr/include/sys/null.h
add_route.o:	/usr/include/sys/socket.h
add_route.o:	/usr/include/sys/types.h
add_route.o:	/usr/include/sys/ucred.h
add_route.o:	/usr/include/sys/un.h
add_route.o:	/usr/include/unistd.h
add_route.o:	add_route.c
