
udpstat.o:	/usr/include/ansi.h
udpstat.o:	/usr/include/assert.h
udpstat.o:	/usr/include/errno.h
udpstat.o:	/usr/include/fcntl.h
udpstat.o:	/usr/include/inttypes.h
udpstat.o:	/usr/include/limits.h
udpstat.o:	/usr/include/machine/fpu.h
udpstat.o:	/usr/include/machine/interrupt.h
udpstat.o:	/usr/include/machine/mcontext.h
udpstat.o:	/usr/include/machine/stackframe.h
udpstat.o:	/usr/include/minix/com.h
udpstat.o:	/usr/include/minix/config.h
udpstat.o:	/usr/include/minix/const.h
udpstat.o:	/usr/include/minix/devio.h
udpstat.o:	/usr/include/minix/dir.h
udpstat.o:	/usr/include/minix/endpoint.h
udpstat.o:	/usr/include/minix/ioctl.h
udpstat.o:	/usr/include/minix/ipc.h
udpstat.o:	/usr/include/minix/ipcconst.h
udpstat.o:	/usr/include/minix/limits.h
udpstat.o:	/usr/include/minix/queryparam.h
udpstat.o:	/usr/include/minix/safecopies.h
udpstat.o:	/usr/include/minix/sef.h
udpstat.o:	/usr/include/minix/sys_config.h
udpstat.o:	/usr/include/minix/syslib.h
udpstat.o:	/usr/include/minix/sysutil.h
udpstat.o:	/usr/include/minix/type.h
udpstat.o:	/usr/include/minix/types.h
udpstat.o:	/usr/include/minix/u64.h
udpstat.o:	/usr/include/minix/vm.h
udpstat.o:	/usr/include/net/gen/arp_io.h
udpstat.o:	/usr/include/net/gen/eth_hdr.h
udpstat.o:	/usr/include/net/gen/eth_io.h
udpstat.o:	/usr/include/net/gen/ether.h
udpstat.o:	/usr/include/net/gen/icmp.h
udpstat.o:	/usr/include/net/gen/icmp_hdr.h
udpstat.o:	/usr/include/net/gen/in.h
udpstat.o:	/usr/include/net/gen/inet.h
udpstat.o:	/usr/include/net/gen/ip_hdr.h
udpstat.o:	/usr/include/net/gen/ip_io.h
udpstat.o:	/usr/include/net/gen/netdb.h
udpstat.o:	/usr/include/net/gen/oneCsum.h
udpstat.o:	/usr/include/net/gen/psip_hdr.h
udpstat.o:	/usr/include/net/gen/psip_io.h
udpstat.o:	/usr/include/net/gen/route.h
udpstat.o:	/usr/include/net/gen/socket.h
udpstat.o:	/usr/include/net/gen/tcp.h
udpstat.o:	/usr/include/net/gen/tcp_hdr.h
udpstat.o:	/usr/include/net/gen/tcp_io.h
udpstat.o:	/usr/include/net/gen/udp.h
udpstat.o:	/usr/include/net/gen/udp_hdr.h
udpstat.o:	/usr/include/net/gen/udp_io.h
udpstat.o:	/usr/include/net/hton.h
udpstat.o:	/usr/include/net/ioctl.h
udpstat.o:	/usr/include/net/netlib.h
udpstat.o:	/usr/include/netinet/in.h
udpstat.o:	/usr/include/stddef.h
udpstat.o:	/usr/include/stdint.h
udpstat.o:	/usr/include/stdio.h
udpstat.o:	/usr/include/stdlib.h
udpstat.o:	/usr/include/string.h
udpstat.o:	/usr/include/sys/cdefs.h
udpstat.o:	/usr/include/sys/ioc_file.h
udpstat.o:	/usr/include/sys/null.h
udpstat.o:	/usr/include/sys/select.h
udpstat.o:	/usr/include/sys/socket.h
udpstat.o:	/usr/include/sys/svrctl.h
udpstat.o:	/usr/include/sys/time.h
udpstat.o:	/usr/include/sys/times.h
udpstat.o:	/usr/include/sys/types.h
udpstat.o:	/usr/include/sys/ucred.h
udpstat.o:	/usr/include/sys/un.h
udpstat.o:	/usr/include/time.h
udpstat.o:	/usr/include/unistd.h
udpstat.o:	/usr/src/servers/inet/const.h
udpstat.o:	/usr/src/servers/inet/generic/buf.h
udpstat.o:	/usr/src/servers/inet/generic/clock.h
udpstat.o:	/usr/src/servers/inet/generic/event.h
udpstat.o:	/usr/src/servers/inet/generic/type.h
udpstat.o:	/usr/src/servers/inet/generic/udp_int.h
udpstat.o:	/usr/src/servers/inet/inet.h
udpstat.o:	/usr/src/servers/inet/inet_config.h
udpstat.o:	udpstat.c
