
rdate.o:	/usr/include/ansi.h
rdate.o:	/usr/include/errno.h
rdate.o:	/usr/include/fcntl.h
rdate.o:	/usr/include/inttypes.h
rdate.o:	/usr/include/limits.h
rdate.o:	/usr/include/machine/interrupt.h
rdate.o:	/usr/include/minix/config.h
rdate.o:	/usr/include/minix/dir.h
rdate.o:	/usr/include/minix/ioctl.h
rdate.o:	/usr/include/minix/limits.h
rdate.o:	/usr/include/minix/sys_config.h
rdate.o:	/usr/include/minix/type.h
rdate.o:	/usr/include/minix/types.h
rdate.o:	/usr/include/net/gen/in.h
rdate.o:	/usr/include/net/gen/netdb.h
rdate.o:	/usr/include/net/gen/socket.h
rdate.o:	/usr/include/net/gen/tcp.h
rdate.o:	/usr/include/net/gen/tcp_io.h
rdate.o:	/usr/include/net/hton.h
rdate.o:	/usr/include/net/ioctl.h
rdate.o:	/usr/include/net/netlib.h
rdate.o:	/usr/include/netinet/in.h
rdate.o:	/usr/include/stddef.h
rdate.o:	/usr/include/stdint.h
rdate.o:	/usr/include/stdio.h
rdate.o:	/usr/include/stdlib.h
rdate.o:	/usr/include/string.h
rdate.o:	/usr/include/sys/cdefs.h
rdate.o:	/usr/include/sys/ioc_cmos.h
rdate.o:	/usr/include/sys/ioc_disk.h
rdate.o:	/usr/include/sys/ioc_file.h
rdate.o:	/usr/include/sys/ioc_memory.h
rdate.o:	/usr/include/sys/ioc_scsi.h
rdate.o:	/usr/include/sys/ioc_sound.h
rdate.o:	/usr/include/sys/ioc_tape.h
rdate.o:	/usr/include/sys/ioc_tty.h
rdate.o:	/usr/include/sys/ioctl.h
rdate.o:	/usr/include/sys/null.h
rdate.o:	/usr/include/sys/socket.h
rdate.o:	/usr/include/sys/types.h
rdate.o:	/usr/include/sys/ucred.h
rdate.o:	/usr/include/sys/un.h
rdate.o:	/usr/include/time.h
rdate.o:	/usr/include/unistd.h
rdate.o:	rdate.c
