
fdisk.o:	/usr/include/ansi.h
fdisk.o:	/usr/include/errno.h
fdisk.o:	/usr/include/fcntl.h
fdisk.o:	/usr/include/limits.h
fdisk.o:	/usr/include/machine/interrupt.h
fdisk.o:	/usr/include/machine/partition.h
fdisk.o:	/usr/include/minix/config.h
fdisk.o:	/usr/include/minix/dir.h
fdisk.o:	/usr/include/minix/ioctl.h
fdisk.o:	/usr/include/minix/limits.h
fdisk.o:	/usr/include/minix/partition.h
fdisk.o:	/usr/include/minix/sys_config.h
fdisk.o:	/usr/include/minix/type.h
fdisk.o:	/usr/include/minix/types.h
fdisk.o:	/usr/include/net/ioctl.h
fdisk.o:	/usr/include/stddef.h
fdisk.o:	/usr/include/stdint.h
fdisk.o:	/usr/include/stdio.h
fdisk.o:	/usr/include/stdlib.h
fdisk.o:	/usr/include/string.h
fdisk.o:	/usr/include/sys/cdefs.h
fdisk.o:	/usr/include/sys/ioc_cmos.h
fdisk.o:	/usr/include/sys/ioc_disk.h
fdisk.o:	/usr/include/sys/ioc_file.h
fdisk.o:	/usr/include/sys/ioc_memory.h
fdisk.o:	/usr/include/sys/ioc_scsi.h
fdisk.o:	/usr/include/sys/ioc_sound.h
fdisk.o:	/usr/include/sys/ioc_tape.h
fdisk.o:	/usr/include/sys/ioc_tty.h
fdisk.o:	/usr/include/sys/ioctl.h
fdisk.o:	/usr/include/sys/null.h
fdisk.o:	/usr/include/sys/stat.h
fdisk.o:	/usr/include/sys/types.h
fdisk.o:	/usr/include/sys/ucred.h
fdisk.o:	/usr/include/sys/un.h
fdisk.o:	/usr/include/unistd.h
fdisk.o:	fdisk.c
