
modem.o:	/usr/include/ansi.h
modem.o:	/usr/include/errno.h
modem.o:	/usr/include/fcntl.h
modem.o:	/usr/include/limits.h
modem.o:	/usr/include/machine/interrupt.h
modem.o:	/usr/include/minix/config.h
modem.o:	/usr/include/minix/dir.h
modem.o:	/usr/include/minix/limits.h
modem.o:	/usr/include/minix/paths.h
modem.o:	/usr/include/minix/sys_config.h
modem.o:	/usr/include/minix/type.h
modem.o:	/usr/include/minix/types.h
modem.o:	/usr/include/signal.h
modem.o:	/usr/include/stddef.h
modem.o:	/usr/include/stdint.h
modem.o:	/usr/include/stdio.h
modem.o:	/usr/include/stdlib.h
modem.o:	/usr/include/string.h
modem.o:	/usr/include/sys/cdefs.h
modem.o:	/usr/include/sys/null.h
modem.o:	/usr/include/sys/stat.h
modem.o:	/usr/include/sys/types.h
modem.o:	/usr/include/sys/ucred.h
modem.o:	/usr/include/sys/wait.h
modem.o:	/usr/include/unistd.h
modem.o:	/usr/include/utmp.h
modem.o:	modem.c
