
hostaddr.o:	/usr/include/ansi.h
hostaddr.o:	/usr/include/errno.h
hostaddr.o:	/usr/include/fcntl.h
hostaddr.o:	/usr/include/inttypes.h
hostaddr.o:	/usr/include/limits.h
hostaddr.o:	/usr/include/machine/interrupt.h
hostaddr.o:	/usr/include/minix/config.h
hostaddr.o:	/usr/include/minix/dir.h
hostaddr.o:	/usr/include/minix/ioctl.h
hostaddr.o:	/usr/include/minix/limits.h
hostaddr.o:	/usr/include/minix/paths.h
hostaddr.o:	/usr/include/minix/sys_config.h
hostaddr.o:	/usr/include/minix/type.h
hostaddr.o:	/usr/include/minix/types.h
hostaddr.o:	/usr/include/net/gen/dhcp.h
hostaddr.o:	/usr/include/net/gen/eth_io.h
hostaddr.o:	/usr/include/net/gen/ether.h
hostaddr.o:	/usr/include/net/gen/if_ether.h
hostaddr.o:	/usr/include/net/gen/in.h
hostaddr.o:	/usr/include/net/gen/inet.h
hostaddr.o:	/usr/include/net/gen/ip_io.h
hostaddr.o:	/usr/include/net/gen/nameser.h
hostaddr.o:	/usr/include/net/gen/netdb.h
hostaddr.o:	/usr/include/net/gen/resolv.h
hostaddr.o:	/usr/include/net/gen/socket.h
hostaddr.o:	/usr/include/net/hton.h
hostaddr.o:	/usr/include/net/ioctl.h
hostaddr.o:	/usr/include/net/netlib.h
hostaddr.o:	/usr/include/netinet/in.h
hostaddr.o:	/usr/include/stddef.h
hostaddr.o:	/usr/include/stdint.h
hostaddr.o:	/usr/include/stdio.h
hostaddr.o:	/usr/include/stdlib.h
hostaddr.o:	/usr/include/string.h
hostaddr.o:	/usr/include/sys/cdefs.h
hostaddr.o:	/usr/include/sys/ioc_cmos.h
hostaddr.o:	/usr/include/sys/ioc_disk.h
hostaddr.o:	/usr/include/sys/ioc_file.h
hostaddr.o:	/usr/include/sys/ioc_memory.h
hostaddr.o:	/usr/include/sys/ioc_scsi.h
hostaddr.o:	/usr/include/sys/ioc_sound.h
hostaddr.o:	/usr/include/sys/ioc_tape.h
hostaddr.o:	/usr/include/sys/ioc_tty.h
hostaddr.o:	/usr/include/sys/ioctl.h
hostaddr.o:	/usr/include/sys/null.h
hostaddr.o:	/usr/include/sys/socket.h
hostaddr.o:	/usr/include/sys/types.h
hostaddr.o:	/usr/include/sys/ucred.h
hostaddr.o:	/usr/include/sys/un.h
hostaddr.o:	/usr/include/sys/utsname.h
hostaddr.o:	/usr/include/unistd.h
hostaddr.o:	hostaddr.c
