
postmort.o:	/usr/include/a.out.h
postmort.o:	/usr/include/ansi.h
postmort.o:	/usr/include/ctype.h
postmort.o:	/usr/include/errno.h
postmort.o:	/usr/include/fcntl.h
postmort.o:	/usr/include/limits.h
postmort.o:	/usr/include/machine/archtypes.h
postmort.o:	/usr/include/machine/fpu.h
postmort.o:	/usr/include/machine/interrupt.h
postmort.o:	/usr/include/machine/stackframe.h
postmort.o:	/usr/include/minix/a.out.h
postmort.o:	/usr/include/minix/bitmap.h
postmort.o:	/usr/include/minix/com.h
postmort.o:	/usr/include/minix/config.h
postmort.o:	/usr/include/minix/const.h
postmort.o:	/usr/include/minix/debug.h
postmort.o:	/usr/include/minix/dir.h
postmort.o:	/usr/include/minix/ipc.h
postmort.o:	/usr/include/minix/ipcconst.h
postmort.o:	/usr/include/minix/limits.h
postmort.o:	/usr/include/minix/portio.h
postmort.o:	/usr/include/minix/priv.h
postmort.o:	/usr/include/minix/sys_config.h
postmort.o:	/usr/include/minix/type.h
postmort.o:	/usr/include/minix/types.h
postmort.o:	/usr/include/signal.h
postmort.o:	/usr/include/stddef.h
postmort.o:	/usr/include/stdint.h
postmort.o:	/usr/include/stdio.h
postmort.o:	/usr/include/stdlib.h
postmort.o:	/usr/include/string.h
postmort.o:	/usr/include/sys/cdefs.h
postmort.o:	/usr/include/sys/null.h
postmort.o:	/usr/include/sys/types.h
postmort.o:	/usr/include/sys/ucred.h
postmort.o:	/usr/include/timers.h
postmort.o:	/usr/include/unistd.h
postmort.o:	/usr/src/kernel/config.h
postmort.o:	/usr/src/kernel/const.h
postmort.o:	/usr/src/kernel/debug.h
postmort.o:	/usr/src/kernel/priv.h
postmort.o:	/usr/src/kernel/proc.h
postmort.o:	/usr/src/kernel/type.h
postmort.o:	/usr/src/servers/pm/const.h
postmort.o:	/usr/src/servers/pm/mproc.h
postmort.o:	postmort.c
