
ifconfig.o:	/usr/include/ansi.h
ifconfig.o:	/usr/include/assert.h
ifconfig.o:	/usr/include/errno.h
ifconfig.o:	/usr/include/fcntl.h
ifconfig.o:	/usr/include/limits.h
ifconfig.o:	/usr/include/machine/interrupt.h
ifconfig.o:	/usr/include/minix/config.h
ifconfig.o:	/usr/include/minix/dir.h
ifconfig.o:	/usr/include/minix/ioctl.h
ifconfig.o:	/usr/include/minix/limits.h
ifconfig.o:	/usr/include/minix/sys_config.h
ifconfig.o:	/usr/include/minix/type.h
ifconfig.o:	/usr/include/minix/types.h
ifconfig.o:	/usr/include/net/gen/in.h
ifconfig.o:	/usr/include/net/gen/inet.h
ifconfig.o:	/usr/include/net/gen/ip_io.h
ifconfig.o:	/usr/include/net/ioctl.h
ifconfig.o:	/usr/include/net/netlib.h
ifconfig.o:	/usr/include/stddef.h
ifconfig.o:	/usr/include/stdint.h
ifconfig.o:	/usr/include/stdio.h
ifconfig.o:	/usr/include/stdlib.h
ifconfig.o:	/usr/include/string.h
ifconfig.o:	/usr/include/sys/cdefs.h
ifconfig.o:	/usr/include/sys/ioc_cmos.h
ifconfig.o:	/usr/include/sys/ioc_disk.h
ifconfig.o:	/usr/include/sys/ioc_file.h
ifconfig.o:	/usr/include/sys/ioc_memory.h
ifconfig.o:	/usr/include/sys/ioc_scsi.h
ifconfig.o:	/usr/include/sys/ioc_sound.h
ifconfig.o:	/usr/include/sys/ioc_tape.h
ifconfig.o:	/usr/include/sys/ioc_tty.h
ifconfig.o:	/usr/include/sys/ioctl.h
ifconfig.o:	/usr/include/sys/null.h
ifconfig.o:	/usr/include/sys/types.h
ifconfig.o:	/usr/include/sys/ucred.h
ifconfig.o:	/usr/include/sys/un.h
ifconfig.o:	/usr/include/unistd.h
ifconfig.o:	ifconfig.c
