
bios_wini.o:	/usr/include/ansi.h
bios_wini.o:	/usr/include/assert.h
bios_wini.o:	/usr/include/errno.h
bios_wini.o:	/usr/include/limits.h
bios_wini.o:	/usr/include/machine/bios.h
bios_wini.o:	/usr/include/machine/fpu.h
bios_wini.o:	/usr/include/machine/int86.h
bios_wini.o:	/usr/include/machine/interrupt.h
bios_wini.o:	/usr/include/machine/mcontext.h
bios_wini.o:	/usr/include/machine/partition.h
bios_wini.o:	/usr/include/machine/ports.h
bios_wini.o:	/usr/include/machine/stackframe.h
bios_wini.o:	/usr/include/minix/bitmap.h
bios_wini.o:	/usr/include/minix/callnr.h
bios_wini.o:	/usr/include/minix/com.h
bios_wini.o:	/usr/include/minix/config.h
bios_wini.o:	/usr/include/minix/const.h
bios_wini.o:	/usr/include/minix/devio.h
bios_wini.o:	/usr/include/minix/dir.h
bios_wini.o:	/usr/include/minix/dmap.h
bios_wini.o:	/usr/include/minix/driver.h
bios_wini.o:	/usr/include/minix/drivers.h
bios_wini.o:	/usr/include/minix/drvlib.h
bios_wini.o:	/usr/include/minix/endpoint.h
bios_wini.o:	/usr/include/minix/ioctl.h
bios_wini.o:	/usr/include/minix/ipc.h
bios_wini.o:	/usr/include/minix/ipcconst.h
bios_wini.o:	/usr/include/minix/limits.h
bios_wini.o:	/usr/include/minix/partition.h
bios_wini.o:	/usr/include/minix/safecopies.h
bios_wini.o:	/usr/include/minix/sef.h
bios_wini.o:	/usr/include/minix/spin.h
bios_wini.o:	/usr/include/minix/sys_config.h
bios_wini.o:	/usr/include/minix/syslib.h
bios_wini.o:	/usr/include/minix/sysutil.h
bios_wini.o:	/usr/include/minix/timers.h
bios_wini.o:	/usr/include/minix/type.h
bios_wini.o:	/usr/include/minix/types.h
bios_wini.o:	/usr/include/minix/u64.h
bios_wini.o:	/usr/include/minix/vm.h
bios_wini.o:	/usr/include/signal.h
bios_wini.o:	/usr/include/stddef.h
bios_wini.o:	/usr/include/stdint.h
bios_wini.o:	/usr/include/stdio.h
bios_wini.o:	/usr/include/stdlib.h
bios_wini.o:	/usr/include/string.h
bios_wini.o:	/usr/include/sys/cdefs.h
bios_wini.o:	/usr/include/sys/ioc_disk.h
bios_wini.o:	/usr/include/sys/null.h
bios_wini.o:	/usr/include/sys/param.h
bios_wini.o:	/usr/include/sys/types.h
bios_wini.o:	/usr/include/sys/ucred.h
bios_wini.o:	/usr/include/timers.h
bios_wini.o:	/usr/include/unistd.h
bios_wini.o:	bios_wini.c
