
du.o:	/usr/include/ansi.h
du.o:	/usr/include/dirent.h
du.o:	/usr/include/errno.h
du.o:	/usr/include/fcntl.h
du.o:	/usr/include/limits.h
du.o:	/usr/include/machine/interrupt.h
du.o:	/usr/include/minix/config.h
du.o:	/usr/include/minix/const.h
du.o:	/usr/include/minix/dir.h
du.o:	/usr/include/minix/dirent.h
du.o:	/usr/include/minix/limits.h
du.o:	/usr/include/minix/sys_config.h
du.o:	/usr/include/minix/type.h
du.o:	/usr/include/minix/types.h
du.o:	/usr/include/stddef.h
du.o:	/usr/include/stdint.h
du.o:	/usr/include/stdio.h
du.o:	/usr/include/stdlib.h
du.o:	/usr/include/string.h
du.o:	/usr/include/sys/cdefs.h
du.o:	/usr/include/sys/null.h
du.o:	/usr/include/sys/stat.h
du.o:	/usr/include/sys/statfs.h
du.o:	/usr/include/sys/types.h
du.o:	/usr/include/sys/ucred.h
du.o:	/usr/include/unistd.h
du.o:	/usr/src/servers/mfs/const.h
du.o:	du.c
