
gcov-pull.o:	/usr/include/alloca.h
gcov-pull.o:	/usr/include/ansi.h
gcov-pull.o:	/usr/include/assert.h
gcov-pull.o:	/usr/include/errno.h
gcov-pull.o:	/usr/include/fcntl.h
gcov-pull.o:	/usr/include/lib.h
gcov-pull.o:	/usr/include/limits.h
gcov-pull.o:	/usr/include/machine/fpu.h
gcov-pull.o:	/usr/include/machine/interrupt.h
gcov-pull.o:	/usr/include/machine/mcontext.h
gcov-pull.o:	/usr/include/machine/stackframe.h
gcov-pull.o:	/usr/include/minix/callnr.h
gcov-pull.o:	/usr/include/minix/com.h
gcov-pull.o:	/usr/include/minix/config.h
gcov-pull.o:	/usr/include/minix/const.h
gcov-pull.o:	/usr/include/minix/devio.h
gcov-pull.o:	/usr/include/minix/dir.h
gcov-pull.o:	/usr/include/minix/endpoint.h
gcov-pull.o:	/usr/include/minix/gcov.h
gcov-pull.o:	/usr/include/minix/ipc.h
gcov-pull.o:	/usr/include/minix/ipcconst.h
gcov-pull.o:	/usr/include/minix/limits.h
gcov-pull.o:	/usr/include/minix/safecopies.h
gcov-pull.o:	/usr/include/minix/sef.h
gcov-pull.o:	/usr/include/minix/sys_config.h
gcov-pull.o:	/usr/include/minix/syslib.h
gcov-pull.o:	/usr/include/minix/type.h
gcov-pull.o:	/usr/include/minix/types.h
gcov-pull.o:	/usr/include/minix/u64.h
gcov-pull.o:	/usr/include/minix/vm.h
gcov-pull.o:	/usr/include/stddef.h
gcov-pull.o:	/usr/include/stdint.h
gcov-pull.o:	/usr/include/stdio.h
gcov-pull.o:	/usr/include/stdlib.h
gcov-pull.o:	/usr/include/string.h
gcov-pull.o:	/usr/include/sys/cdefs.h
gcov-pull.o:	/usr/include/sys/null.h
gcov-pull.o:	/usr/include/sys/types.h
gcov-pull.o:	/usr/include/sys/ucred.h
gcov-pull.o:	/usr/include/unistd.h
gcov-pull.o:	gcov-pull.c
