
fsck1.o:	/usr/include/ansi.h
fsck1.o:	/usr/include/ctype.h
fsck1.o:	/usr/include/dirent.h
fsck1.o:	/usr/include/errno.h
fsck1.o:	/usr/include/fcntl.h
fsck1.o:	/usr/include/limits.h
fsck1.o:	/usr/include/machine/interrupt.h
fsck1.o:	/usr/include/minix/config.h
fsck1.o:	/usr/include/minix/const.h
fsck1.o:	/usr/include/minix/dir.h
fsck1.o:	/usr/include/minix/dirent.h
fsck1.o:	/usr/include/minix/fslib.h
fsck1.o:	/usr/include/minix/limits.h
fsck1.o:	/usr/include/minix/sys_config.h
fsck1.o:	/usr/include/minix/type.h
fsck1.o:	/usr/include/minix/types.h
fsck1.o:	/usr/include/stddef.h
fsck1.o:	/usr/include/stdint.h
fsck1.o:	/usr/include/stdio.h
fsck1.o:	/usr/include/stdlib.h
fsck1.o:	/usr/include/string.h
fsck1.o:	/usr/include/sys/cdefs.h
fsck1.o:	/usr/include/sys/dir.h
fsck1.o:	/usr/include/sys/null.h
fsck1.o:	/usr/include/sys/queue.h
fsck1.o:	/usr/include/sys/types.h
fsck1.o:	/usr/include/sys/ucred.h
fsck1.o:	/usr/include/unistd.h
fsck1.o:	/usr/src/servers/mfs/const.h
fsck1.o:	/usr/src/servers/mfs/inode.h
fsck1.o:	/usr/src/servers/mfs/super.h
fsck1.o:	/usr/src/servers/mfs/type.h
fsck1.o:	fsck1.c
