
loadfont.o:	/usr/include/ansi.h
loadfont.o:	/usr/include/errno.h
loadfont.o:	/usr/include/fcntl.h
loadfont.o:	/usr/include/limits.h
loadfont.o:	/usr/include/machine/interrupt.h
loadfont.o:	/usr/include/minix/config.h
loadfont.o:	/usr/include/minix/dir.h
loadfont.o:	/usr/include/minix/ioctl.h
loadfont.o:	/usr/include/minix/limits.h
loadfont.o:	/usr/include/minix/sys_config.h
loadfont.o:	/usr/include/minix/type.h
loadfont.o:	/usr/include/minix/types.h
loadfont.o:	/usr/include/net/ioctl.h
loadfont.o:	/usr/include/stddef.h
loadfont.o:	/usr/include/stdint.h
loadfont.o:	/usr/include/stdlib.h
loadfont.o:	/usr/include/string.h
loadfont.o:	/usr/include/sys/cdefs.h
loadfont.o:	/usr/include/sys/ioc_cmos.h
loadfont.o:	/usr/include/sys/ioc_disk.h
loadfont.o:	/usr/include/sys/ioc_file.h
loadfont.o:	/usr/include/sys/ioc_memory.h
loadfont.o:	/usr/include/sys/ioc_scsi.h
loadfont.o:	/usr/include/sys/ioc_sound.h
loadfont.o:	/usr/include/sys/ioc_tape.h
loadfont.o:	/usr/include/sys/ioc_tty.h
loadfont.o:	/usr/include/sys/ioctl.h
loadfont.o:	/usr/include/sys/null.h
loadfont.o:	/usr/include/sys/types.h
loadfont.o:	/usr/include/sys/ucred.h
loadfont.o:	/usr/include/sys/un.h
loadfont.o:	/usr/include/termios.h
loadfont.o:	/usr/include/unistd.h
loadfont.o:	loadfont.c
