
synctree.o:	/usr/include/ansi.h
synctree.o:	/usr/include/dirent.h
synctree.o:	/usr/include/errno.h
synctree.o:	/usr/include/fcntl.h
synctree.o:	/usr/include/limits.h
synctree.o:	/usr/include/machine/interrupt.h
synctree.o:	/usr/include/minix/config.h
synctree.o:	/usr/include/minix/dir.h
synctree.o:	/usr/include/minix/dirent.h
synctree.o:	/usr/include/minix/limits.h
synctree.o:	/usr/include/minix/sys_config.h
synctree.o:	/usr/include/minix/type.h
synctree.o:	/usr/include/minix/types.h
synctree.o:	/usr/include/signal.h
synctree.o:	/usr/include/stddef.h
synctree.o:	/usr/include/stdint.h
synctree.o:	/usr/include/stdio.h
synctree.o:	/usr/include/stdlib.h
synctree.o:	/usr/include/string.h
synctree.o:	/usr/include/sys/cdefs.h
synctree.o:	/usr/include/sys/null.h
synctree.o:	/usr/include/sys/stat.h
synctree.o:	/usr/include/sys/types.h
synctree.o:	/usr/include/sys/ucred.h
synctree.o:	/usr/include/sys/wait.h
synctree.o:	/usr/include/time.h
synctree.o:	/usr/include/unistd.h
synctree.o:	/usr/include/utime.h
synctree.o:	synctree.c
