
mt.o:	/usr/include/ansi.h
mt.o:	/usr/include/errno.h
mt.o:	/usr/include/fcntl.h
mt.o:	/usr/include/limits.h
mt.o:	/usr/include/machine/interrupt.h
mt.o:	/usr/include/minix/config.h
mt.o:	/usr/include/minix/dir.h
mt.o:	/usr/include/minix/ioctl.h
mt.o:	/usr/include/minix/limits.h
mt.o:	/usr/include/minix/sys_config.h
mt.o:	/usr/include/minix/type.h
mt.o:	/usr/include/minix/types.h
mt.o:	/usr/include/net/ioctl.h
mt.o:	/usr/include/stddef.h
mt.o:	/usr/include/stdint.h
mt.o:	/usr/include/stdio.h
mt.o:	/usr/include/stdlib.h
mt.o:	/usr/include/string.h
mt.o:	/usr/include/sys/cdefs.h
mt.o:	/usr/include/sys/ioc_cmos.h
mt.o:	/usr/include/sys/ioc_disk.h
mt.o:	/usr/include/sys/ioc_file.h
mt.o:	/usr/include/sys/ioc_memory.h
mt.o:	/usr/include/sys/ioc_scsi.h
mt.o:	/usr/include/sys/ioc_sound.h
mt.o:	/usr/include/sys/ioc_tape.h
mt.o:	/usr/include/sys/ioc_tty.h
mt.o:	/usr/include/sys/ioctl.h
mt.o:	/usr/include/sys/mtio.h
mt.o:	/usr/include/sys/null.h
mt.o:	/usr/include/sys/types.h
mt.o:	/usr/include/sys/ucred.h
mt.o:	/usr/include/sys/un.h
mt.o:	/usr/include/unistd.h
mt.o:	mt.c
