
stty.o:	/usr/include/ansi.h
stty.o:	/usr/include/assert.h
stty.o:	/usr/include/ctype.h
stty.o:	/usr/include/errno.h
stty.o:	/usr/include/limits.h
stty.o:	/usr/include/minix/dir.h
stty.o:	/usr/include/minix/ioctl.h
stty.o:	/usr/include/minix/limits.h
stty.o:	/usr/include/minix/sys_config.h
stty.o:	/usr/include/minix/types.h
stty.o:	/usr/include/net/ioctl.h
stty.o:	/usr/include/stddef.h
stty.o:	/usr/include/stdint.h
stty.o:	/usr/include/stdio.h
stty.o:	/usr/include/stdlib.h
stty.o:	/usr/include/string.h
stty.o:	/usr/include/sys/cdefs.h
stty.o:	/usr/include/sys/ioc_cmos.h
stty.o:	/usr/include/sys/ioc_disk.h
stty.o:	/usr/include/sys/ioc_file.h
stty.o:	/usr/include/sys/ioc_memory.h
stty.o:	/usr/include/sys/ioc_scsi.h
stty.o:	/usr/include/sys/ioc_sound.h
stty.o:	/usr/include/sys/ioc_tape.h
stty.o:	/usr/include/sys/ioc_tty.h
stty.o:	/usr/include/sys/ioctl.h
stty.o:	/usr/include/sys/null.h
stty.o:	/usr/include/sys/types.h
stty.o:	/usr/include/sys/un.h
stty.o:	/usr/include/termios.h
stty.o:	stty.c
