
padtext.o:	/usr/include/ansi.h
padtext.o:	/usr/include/assert.h
padtext.o:	/usr/include/errno.h
padtext.o:	/usr/include/fcntl.h
padtext.o:	/usr/include/limits.h
padtext.o:	/usr/include/machine/interrupt.h
padtext.o:	/usr/include/minix/a.out.h
padtext.o:	/usr/include/minix/config.h
padtext.o:	/usr/include/minix/const.h
padtext.o:	/usr/include/minix/dir.h
padtext.o:	/usr/include/minix/limits.h
padtext.o:	/usr/include/minix/sys_config.h
padtext.o:	/usr/include/minix/type.h
padtext.o:	/usr/include/minix/types.h
padtext.o:	/usr/include/stddef.h
padtext.o:	/usr/include/stdint.h
padtext.o:	/usr/include/stdio.h
padtext.o:	/usr/include/stdlib.h
padtext.o:	/usr/include/string.h
padtext.o:	/usr/include/sys/cdefs.h
padtext.o:	/usr/include/sys/null.h
padtext.o:	/usr/include/sys/ucred.h
padtext.o:	/usr/include/unistd.h
padtext.o:	padtext.c
