
ipcrm.o:	/usr/include/ansi.h
ipcrm.o:	/usr/include/ctype.h
ipcrm.o:	/usr/include/errno.h
ipcrm.o:	/usr/include/limits.h
ipcrm.o:	/usr/include/machine/interrupt.h
ipcrm.o:	/usr/include/minix/config.h
ipcrm.o:	/usr/include/minix/dir.h
ipcrm.o:	/usr/include/minix/limits.h
ipcrm.o:	/usr/include/minix/sys_config.h
ipcrm.o:	/usr/include/minix/type.h
ipcrm.o:	/usr/include/minix/types.h
ipcrm.o:	/usr/include/stddef.h
ipcrm.o:	/usr/include/stdint.h
ipcrm.o:	/usr/include/stdio.h
ipcrm.o:	/usr/include/stdlib.h
ipcrm.o:	/usr/include/string.h
ipcrm.o:	/usr/include/sys/cdefs.h
ipcrm.o:	/usr/include/sys/ipc.h
ipcrm.o:	/usr/include/sys/null.h
ipcrm.o:	/usr/include/sys/sem.h
ipcrm.o:	/usr/include/sys/shm.h
ipcrm.o:	/usr/include/sys/types.h
ipcrm.o:	/usr/include/sys/ucred.h
ipcrm.o:	/usr/include/unistd.h
ipcrm.o:	ipcrm.c
