
env.o:	/usr/include/ansi.h
env.o:	/usr/include/errno.h
env.o:	/usr/include/limits.h
env.o:	/usr/include/machine/interrupt.h
env.o:	/usr/include/minix/config.h
env.o:	/usr/include/minix/dir.h
env.o:	/usr/include/minix/limits.h
env.o:	/usr/include/minix/sys_config.h
env.o:	/usr/include/minix/type.h
env.o:	/usr/include/minix/types.h
env.o:	/usr/include/stddef.h
env.o:	/usr/include/stdint.h
env.o:	/usr/include/stdio.h
env.o:	/usr/include/stdlib.h
env.o:	/usr/include/string.h
env.o:	/usr/include/sys/cdefs.h
env.o:	/usr/include/sys/null.h
env.o:	/usr/include/sys/types.h
env.o:	/usr/include/sys/ucred.h
env.o:	/usr/include/unistd.h
env.o:	env.c
