
write.o:	/usr/include/ansi.h
write.o:	/usr/include/fcntl.h
write.o:	/usr/include/limits.h
write.o:	/usr/include/machine/interrupt.h
write.o:	/usr/include/minix/config.h
write.o:	/usr/include/minix/dir.h
write.o:	/usr/include/minix/limits.h
write.o:	/usr/include/minix/paths.h
write.o:	/usr/include/minix/sys_config.h
write.o:	/usr/include/minix/type.h
write.o:	/usr/include/minix/types.h
write.o:	/usr/include/pwd.h
write.o:	/usr/include/signal.h
write.o:	/usr/include/stddef.h
write.o:	/usr/include/stdint.h
write.o:	/usr/include/stdio.h
write.o:	/usr/include/stdlib.h
write.o:	/usr/include/string.h
write.o:	/usr/include/sys/cdefs.h
write.o:	/usr/include/sys/null.h
write.o:	/usr/include/sys/types.h
write.o:	/usr/include/sys/ucred.h
write.o:	/usr/include/termios.h
write.o:	/usr/include/time.h
write.o:	/usr/include/unistd.h
write.o:	/usr/include/utmp.h
write.o:	write.c
