
eject.o:	/usr/include/ansi.h
eject.o:	/usr/include/errno.h
eject.o:	/usr/include/fcntl.h
eject.o:	/usr/include/limits.h
eject.o:	/usr/include/minix/dir.h
eject.o:	/usr/include/minix/ioctl.h
eject.o:	/usr/include/minix/limits.h
eject.o:	/usr/include/minix/sys_config.h
eject.o:	/usr/include/minix/types.h
eject.o:	/usr/include/net/ioctl.h
eject.o:	/usr/include/stddef.h
eject.o:	/usr/include/stdint.h
eject.o:	/usr/include/stdio.h
eject.o:	/usr/include/stdlib.h
eject.o:	/usr/include/string.h
eject.o:	/usr/include/sys/cdefs.h
eject.o:	/usr/include/sys/ioc_cmos.h
eject.o:	/usr/include/sys/ioc_disk.h
eject.o:	/usr/include/sys/ioc_file.h
eject.o:	/usr/include/sys/ioc_memory.h
eject.o:	/usr/include/sys/ioc_scsi.h
eject.o:	/usr/include/sys/ioc_sound.h
eject.o:	/usr/include/sys/ioc_tape.h
eject.o:	/usr/include/sys/ioc_tty.h
eject.o:	/usr/include/sys/ioctl.h
eject.o:	/usr/include/sys/null.h
eject.o:	/usr/include/sys/types.h
eject.o:	/usr/include/sys/un.h
eject.o:	eject.c
