
mixer.o:	/usr/include/ansi.h
mixer.o:	/usr/include/curses.h
mixer.o:	/usr/include/errno.h
mixer.o:	/usr/include/fcntl.h
mixer.o:	/usr/include/limits.h
mixer.o:	/usr/include/machine/interrupt.h
mixer.o:	/usr/include/minix/config.h
mixer.o:	/usr/include/minix/dir.h
mixer.o:	/usr/include/minix/ioctl.h
mixer.o:	/usr/include/minix/limits.h
mixer.o:	/usr/include/minix/sound.h
mixer.o:	/usr/include/minix/sys_config.h
mixer.o:	/usr/include/minix/type.h
mixer.o:	/usr/include/minix/types.h
mixer.o:	/usr/include/net/ioctl.h
mixer.o:	/usr/include/signal.h
mixer.o:	/usr/include/stdarg.h
mixer.o:	/usr/include/stddef.h
mixer.o:	/usr/include/stdint.h
mixer.o:	/usr/include/stdio.h
mixer.o:	/usr/include/stdlib.h
mixer.o:	/usr/include/string.h
mixer.o:	/usr/include/sys/cdefs.h
mixer.o:	/usr/include/sys/ioc_cmos.h
mixer.o:	/usr/include/sys/ioc_disk.h
mixer.o:	/usr/include/sys/ioc_file.h
mixer.o:	/usr/include/sys/ioc_memory.h
mixer.o:	/usr/include/sys/ioc_scsi.h
mixer.o:	/usr/include/sys/ioc_sound.h
mixer.o:	/usr/include/sys/ioc_tape.h
mixer.o:	/usr/include/sys/ioc_tty.h
mixer.o:	/usr/include/sys/ioctl.h
mixer.o:	/usr/include/sys/null.h
mixer.o:	/usr/include/sys/types.h
mixer.o:	/usr/include/sys/ucred.h
mixer.o:	/usr/include/sys/un.h
mixer.o:	/usr/include/termios.h
mixer.o:	/usr/include/unistd.h
mixer.o:	mixer.c
