
ls.o:	/usr/include/ansi.h
ls.o:	/usr/include/dirent.h
ls.o:	/usr/include/errno.h
ls.o:	/usr/include/fcntl.h
ls.o:	/usr/include/grp.h
ls.o:	/usr/include/limits.h
ls.o:	/usr/include/machine/interrupt.h
ls.o:	/usr/include/minix/config.h
ls.o:	/usr/include/minix/dir.h
ls.o:	/usr/include/minix/dirent.h
ls.o:	/usr/include/minix/ioctl.h
ls.o:	/usr/include/minix/limits.h
ls.o:	/usr/include/minix/sys_config.h
ls.o:	/usr/include/minix/type.h
ls.o:	/usr/include/minix/types.h
ls.o:	/usr/include/net/ioctl.h
ls.o:	/usr/include/pwd.h
ls.o:	/usr/include/stddef.h
ls.o:	/usr/include/stdint.h
ls.o:	/usr/include/stdio.h
ls.o:	/usr/include/stdlib.h
ls.o:	/usr/include/string.h
ls.o:	/usr/include/sys/cdefs.h
ls.o:	/usr/include/sys/ioc_cmos.h
ls.o:	/usr/include/sys/ioc_disk.h
ls.o:	/usr/include/sys/ioc_file.h
ls.o:	/usr/include/sys/ioc_memory.h
ls.o:	/usr/include/sys/ioc_scsi.h
ls.o:	/usr/include/sys/ioc_sound.h
ls.o:	/usr/include/sys/ioc_tape.h
ls.o:	/usr/include/sys/ioc_tty.h
ls.o:	/usr/include/sys/ioctl.h
ls.o:	/usr/include/sys/null.h
ls.o:	/usr/include/sys/stat.h
ls.o:	/usr/include/sys/types.h
ls.o:	/usr/include/sys/ucred.h
ls.o:	/usr/include/sys/un.h
ls.o:	/usr/include/termios.h
ls.o:	/usr/include/time.h
ls.o:	/usr/include/unistd.h
ls.o:	ls.c
