
rget.o:	/usr/include/ansi.h
rget.o:	/usr/include/errno.h
rget.o:	/usr/include/fcntl.h
rget.o:	/usr/include/inttypes.h
rget.o:	/usr/include/limits.h
rget.o:	/usr/include/machine/interrupt.h
rget.o:	/usr/include/minix/config.h
rget.o:	/usr/include/minix/dir.h
rget.o:	/usr/include/minix/ioctl.h
rget.o:	/usr/include/minix/limits.h
rget.o:	/usr/include/minix/sys_config.h
rget.o:	/usr/include/minix/type.h
rget.o:	/usr/include/minix/types.h
rget.o:	/usr/include/net/gen/in.h
rget.o:	/usr/include/net/gen/inet.h
rget.o:	/usr/include/net/gen/netdb.h
rget.o:	/usr/include/net/gen/socket.h
rget.o:	/usr/include/net/gen/tcp.h
rget.o:	/usr/include/net/gen/tcp_hdr.h
rget.o:	/usr/include/net/gen/tcp_io.h
rget.o:	/usr/include/net/hton.h
rget.o:	/usr/include/net/ioctl.h
rget.o:	/usr/include/net/netlib.h
rget.o:	/usr/include/netinet/in.h
rget.o:	/usr/include/stddef.h
rget.o:	/usr/include/stdint.h
rget.o:	/usr/include/stdio.h
rget.o:	/usr/include/stdlib.h
rget.o:	/usr/include/string.h
rget.o:	/usr/include/sys/cdefs.h
rget.o:	/usr/include/sys/ioc_cmos.h
rget.o:	/usr/include/sys/ioc_disk.h
rget.o:	/usr/include/sys/ioc_file.h
rget.o:	/usr/include/sys/ioc_memory.h
rget.o:	/usr/include/sys/ioc_scsi.h
rget.o:	/usr/include/sys/ioc_sound.h
rget.o:	/usr/include/sys/ioc_tape.h
rget.o:	/usr/include/sys/ioc_tty.h
rget.o:	/usr/include/sys/ioctl.h
rget.o:	/usr/include/sys/null.h
rget.o:	/usr/include/sys/socket.h
rget.o:	/usr/include/sys/types.h
rget.o:	/usr/include/sys/ucred.h
rget.o:	/usr/include/sys/un.h
rget.o:	/usr/include/unistd.h
rget.o:	rget.c
